/*
 * SerialCommon.h
 *
 *  Created on: 23 Feb 2026
 *      Author: B4T
 */

#ifndef SERIALSENSOR_SERIALCOMMON_H_
#define SERIALSENSOR_SERIALCOMMON_H_


typedef enum
{
    INIT_ERROR = -1,
    INIT_START_SENSOR,
    INIT_SEND_REQUEST,
    INIT_RECEIVE_DATA,
    INIT_FINISH_SENSOR_1,
    INIT_FINISH_SENSOR_2,
    INIT_FINISH,
}INIT_SENSOR_TYPE_ENUM;


typedef enum
{
    FRAME_LENGTH_ERROR = -2,
    FRAME_CRC_ERROR,
    NO_RESPONSE = 0,
    PROCESSING_FRAME,
    INVALID_DATA,
    NEW_DATA_OUTLIER,
    NEW_DATA,
}SENSOR_PROCESS_MSG_TYPE;

#endif /* SERIALSENSOR_SERIALCOMMON_H_ */
